# Generated by Django 2.2.1 on 2019-09-17 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190917_0230'),
        ('backend', '0004_auto_20190917_0339'),
    ]

    operations = [
    ]
